import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import UserProvider from "@/providers/UserProvider";

import { Toaster } from 'react-hot-toast';
import Header from "./components/header/Header";
import MainContentLayout from "@/providers/MainContentLayout";
import SideBarProvider from "@/providers/SideBarProvider";
import MainLayout from "@/providers/MainLayout";
import MiniSideBar from "./components/miniSideBar/MiniSideBar";

const inter = Inter({
    subsets: ['cyrillic', 'latin']
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
                    integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
                    crossOrigin="anonymous"
                    referrerPolicy="no-referrer"
                />
            </head>
            <body className={inter.className}>
                <Toaster position="top-center" />
                <UserProvider>
                    <div className="h-full flex overflow-hidden">
                        <MiniSideBar />
                        <div className="flex flex-1 flex-col">
                            <Header />
                            <MainContentLayout>
                                <MainLayout>{children}</MainLayout>
                                <SideBarProvider />
                            </MainContentLayout>
                        </div>
                    </div>
                    {children}
                </UserProvider>
            </body>
        </html>
    );
}
